apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-artemis
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-fuchicorp-prod
spec:
  rules:
  - host: {{ .Values.dns_endpoint }}
    http:
      paths:
      - backend:
          serviceName: {{ .Values.artemis_service }}
          servicePort: {{ .Values.artemis_port }}

  tls:
  - hosts:
    - {{ .Values.dns_endpoint }}
    secretName: letsencrypt-sec-artemis-prod
